// 仅绘制人工标注，不测量图片；位置按任务保存于本机浏览器。
window.mountGarmentAnnotations=function(host,job){
 const input=job.request.size,key='fabric-pig.annotations.v2.'+job.id;
 const names=Object.keys(input.values||{}),units=input.units||{};
 const defaults=names.map((name,i)=>({name,value:String(input.values[name]),unit:units[name]??'cm',kind:input.lineTypes?.[name]||'文字',x:.06,y:.055+i*.05,ax:.2,ay:.2+i*.045,bx:.6,by:.2+i*.045}));
 let rows=defaults;try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.source===JSON.stringify(input))rows=saved.rows;}catch{}
 const section=document.createElement('section');section.className='annotation-editor';host.append(section);
 section.innerHTML='<h3>尺寸线与文字标注</h3><button class="annotation-expand">放大编辑</button><p class="note">尺寸来自人工填写。选择项目后拖动文字或两端圆点，也可输入位置百分比。初始线条仅为示意位置，请调整到对应部位；围度默认文字说明，不自动换算成平铺宽度。已生成任务的编辑保存在本机服务端，下载图片不含控制点。</p><label>当前标注<select class="field annotation-select"></select></label><label>标注方式<select class="field annotation-kind"><option>文字</option><option>横向</option><option>竖向</option><option>斜向</option></select></label><div class="annotation-coordinates" style="display:flex;flex-wrap:wrap;gap:8px"></div><canvas class="live-annotation" aria-label="可编辑尺寸标注画布"></canvas><p class="annotation-message note"></p><button class="annotation-download">下载尺寸标注图</button> <button class="annotation-reset">重置标注位置</button>';
 const select=section.querySelector('.annotation-select'),kind=section.querySelector('.annotation-kind'),coords=section.querySelector('.annotation-coordinates'),canvas=section.querySelector('canvas'),ctx=canvas.getContext('2d'),msg=section.querySelector('.annotation-message'),download=section.querySelector('.annotation-download');
 let active=0,drag=null,loaded=false;download.disabled=true;
 const expand=section.querySelector('.annotation-expand');expand.onclick=()=>{const opened=section.dataset.expanded==='true';section.dataset.expanded=String(!opened);section.style.cssText=opened?'':'position:fixed;inset:20px;z-index:1000;background:white;padding:24px;overflow:auto;box-shadow:0 0 0 30px #0008';canvas.style.cssText=opened?'':'display:block;max-height:75vh;max-width:100%;margin:20px auto';expand.textContent=opened?'放大编辑':'收起编辑';};section.addEventListener('keydown',e=>{if(e.key==='Escape'&&section.dataset.expanded==='true')expand.click();});
 rows.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.name+'：'+r.value+(r.unit?' '+r.unit:'');select.append(o);});
 for(const [field,title]of [['x','文字横向'],['y','文字纵向'],['ax','起点横向'],['ay','起点纵向'],['bx','终点横向'],['by','终点纵向']]){const label=document.createElement('label');label.textContent=title+' %';const el=document.createElement('input');el.type='number';el.min=1;el.max=99;el.step=.1;el.className='field';el.style.width='90px';el.dataset.coordinate=field;label.append(el);coords.append(label);el.oninput=()=>{if(!rows[active]||el.value==='')return;rows[active][field]=Math.max(.01,Math.min(.99,Number(el.value)/100));align(rows[active],field);draw();save();};}
 function align(r,field){if(r.kind==='横向'){if(field==='by')r.ay=r.by;else r.by=r.ay;}if(r.kind==='竖向'){if(field==='bx')r.ax=r.bx;else r.bx=r.ax;}}
 let annotationWrites=Promise.resolve(),edited=false;const persisted=/^[a-f0-9-]{36}$/.test(job.id);
 function save(){edited=true;if(persisted){const body=JSON.stringify({source:JSON.stringify(input),rows});annotationWrites=annotationWrites.then(async()=>{const r=await fetch('/api/annotations/'+job.id,{method:'POST',headers:{'Content-Type':'application/json','X-Workbench':'1'},body});if(!r.ok)throw Error();msg.textContent='标注已保存到本机服务端。';}).catch(()=>{msg.textContent='服务端保存失败，已保留浏览器草稿；请下载图片。';});}
 try{localStorage.setItem(key,JSON.stringify({source:JSON.stringify(input),rows}));msg.textContent='标注已保存到此浏览器。';}catch{msg.textContent='浏览器保存失败，请下载图片保留修改。';}}
 function controls(){const r=rows[active];kind.disabled=!r;kind.value=r?.kind||'文字';coords.querySelectorAll('input').forEach(el=>{el.disabled=!r||(r.kind==='文字'&&!['x','y'].includes(el.dataset.coordinate));el.value=r?Math.round(r[el.dataset.coordinate]*1000)/10:'';});}
 const img=new Image();
 function arrow(x,y,angle){const len=canvas.width*.01;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-len*Math.cos(angle-.45),y-len*Math.sin(angle-.45));ctx.moveTo(x,y);ctx.lineTo(x-len*Math.cos(angle+.45),y-len*Math.sin(angle+.45));ctx.stroke();}
 function draw(edit=true){if(!loaded)return;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);ctx.font=Math.round(w*.019)+'px "PingFang SC",sans-serif';ctx.lineWidth=Math.max(2,w*.0015);rows.forEach((r,i)=>{ctx.strokeStyle='#523c30';ctx.fillStyle='#392c26';if(r.kind!=='文字'){const ax=r.ax*w,ay=r.ay*h,bx=r.bx*w,by=r.by*h;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(bx,by);ctx.stroke();const angle=Math.atan2(by-ay,bx-ax);arrow(bx,by,angle);arrow(ax,ay,angle+Math.PI);const tick=w*.007;ctx.beginPath();for(const [x,y]of [[ax,ay],[bx,by]]){ctx.moveTo(x-tick*Math.sin(angle),y+tick*Math.cos(angle));ctx.lineTo(x+tick*Math.sin(angle),y-tick*Math.cos(angle));}ctx.stroke();if(edit&&i===active){ctx.fillStyle='#b4476a';for(const [x,y]of [[ax,ay],[bx,by]]){ctx.beginPath();ctx.arc(x,y,w*.007,0,Math.PI*2);ctx.fill();}}}const text=r.name+' '+r.value+(r.unit?' '+r.unit:''),x=r.x*w,y=r.y*h,tw=ctx.measureText(text).width;ctx.fillStyle='rgba(255,255,255,.92)';ctx.fillRect(x-5,y-w*.024,tw+10,w*.033);ctx.fillStyle='#392c26';ctx.fillText(text,x,y);});}
 select.onchange=()=>{active=Number(select.value);controls();draw();};kind.onchange=()=>{const r=rows[active];if(!r)return;r.kind=kind.value;if(r.kind==='竖向'){r.bx=r.ax;r.by=Math.min(.95,r.ay+.3);}else if(r.kind==='横向'){r.bx=Math.min(.95,r.ax+.3);r.by=r.ay;}else if(r.kind==='斜向'){r.bx=Math.min(.95,r.ax+.25);r.by=Math.min(.95,r.ay+.2);}controls();draw();save();};
 const point=e=>{const box=canvas.getBoundingClientRect();return {x:Math.max(.01,Math.min(.99,(e.clientX-box.left)/box.width)),y:Math.max(.01,Math.min(.99,(e.clientY-box.top)/box.height))};};
 canvas.onpointerdown=e=>{const p=point(e),r=rows[active];if(!r)return;for(const prefix of ['a','b'])if(r.kind!=='文字'&&Math.hypot((r[prefix+'x']-p.x)*canvas.clientWidth,(r[prefix+'y']-p.y)*canvas.clientHeight)<18)drag=prefix;if(!drag){const i=rows.findIndex(v=>{const tw=ctx.measureText(v.name+' '+v.value+(v.unit?' '+v.unit:'')).width/canvas.width;return Math.abs(p.y-v.y)<.025&&p.x>v.x-.01&&p.x<v.x+tw+.015;});if(i>=0){active=i;select.value=i;drag='';}}if(drag!==null){canvas.setPointerCapture(e.pointerId);e.preventDefault();}};
 canvas.onpointermove=e=>{if(drag===null)return;const p=point(e),r=rows[active];r[drag+'x']=p.x;r[drag+'y']=p.y;align(r,drag+'y');controls();draw();};
 const end=()=>{if(drag!==null)save();drag=null;};canvas.onpointerup=end;canvas.onpointercancel=end;
 section.querySelector('.annotation-reset').onclick=()=>{rows=structuredClone(defaults);active=0;select.value=0;controls();draw();save();};
 download.onclick=()=>{draw(false);canvas.toBlob(blob=>{draw();if(!blob){msg.textContent='导出失败，请重试。';return;}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='尺寸标注图.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');};
 img.onload=()=>{canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;loaded=true;download.disabled=false;draw();};img.onerror=()=>{msg.textContent='底图读取失败，请检查图片。';};img.src=job.result.url;controls();
 if(persisted)fetch('/api/annotations/'+job.id).then(r=>{if(!r.ok)throw Error();return r.json();}).then(saved=>{if(edited)return;if(saved?.source===JSON.stringify(input)){rows=saved.rows;controls();draw();msg.textContent='已恢复本机服务端标注。';}else if(localStorage.getItem(key))save();}).catch(()=>{msg.textContent='标注读取失败，当前使用浏览器草稿。';});
};
