(() => {
 if(location.protocol==='file:')return;
 const api=async(url,body)=>{const r=await fetch(url,{headers:{'Content-Type':'application/json','X-Workbench':'1'},...(body?{method:'POST',body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'读取失败');return d;};
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn)=>{const n=el('button',text);n.onclick=()=>Promise.resolve().then(fn).catch(error);return n;};
 const labels={model:'模特上身图',product:'单品展示图',size:'尺寸标注图'},states={complete:'已完成',failed:'失败',waiting:'待确认',ready:'待审阅',queued:'排队中',generating:'生成中',understanding:'整理中'};
 const workspace=document.querySelector('.workspace'),handle=el('button',undefined,'split-handle');handle.setAttribute('role','separator');handle.setAttribute('aria-label','调整左右区域宽度');handle.setAttribute('aria-orientation','vertical');handle.setAttribute('aria-valuemin','28');handle.setAttribute('aria-valuemax','55');handle.tabIndex=0;workspace.insertBefore(handle,document.querySelector('.preview'));
 function ratio(value){value=Math.max(28,Math.min(55,value));workspace.style.setProperty('--input-width',value+'%');handle.setAttribute('aria-valuenow',Math.round(value));localStorage.setItem('fabric-pig.layout-width',value);}
 ratio(Number(localStorage.getItem('fabric-pig.layout-width'))||40);handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);};handle.onpointermove=e=>{if(handle.hasPointerCapture(e.pointerId)){const r=workspace.getBoundingClientRect();ratio((e.clientX-r.left)/r.width*100);}};handle.onpointerup=e=>handle.releasePointerCapture(e.pointerId);handle.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();ratio(Number(handle.getAttribute('aria-valuenow'))+(e.key==='ArrowLeft'?-2:2));}};
 const admin=document.querySelector('#open-prompt-admin'),actions=el('div',undefined,'header-actions');admin.before(actions);actions.append(button('历史方案',()=>open()),admin);
 const dialog=el('dialog',undefined,'library-dialog');dialog.setAttribute('aria-label','历史方案库');document.body.append(dialog);let list=[],detail=null,current=null,filter={q:'',type:''};let message;let selecting=false;const selected=new Set();
 function error(e){if(message)message.textContent=e.message;else alert(e.message);}
 function top(title){dialog.replaceChildren();const h=el('div',undefined,'library-top');h.append(el('h2',title),button('返回工作台',()=>dialog.close()));dialog.append(h);message=el('p','','library-message');message.setAttribute('role','status');dialog.append(message);return h;}
 async function open(){selecting=false;selected.clear();if(!dialog.open)dialog.showModal();top('历史方案');message.textContent='正在读取已保存方案…';list=await api('/api/designs');renderList();}
 function renderList(){detail=null;const h=top('历史方案');h.append(button(selecting?'取消选择':'批量选择',()=>{selecting=!selecting;selected.clear();renderList();}));const controls=el('div',undefined,'library-filters'),search=el('input');search.className='field';search.placeholder='搜索方案名称';search.setAttribute('aria-label','搜索方案名称');search.value=filter.q;const type=el('select');type.className='field';type.setAttribute('aria-label','筛选图片类型');for(const [v,t]of [['','全部类型'],...Object.entries(labels)]){const o=el('option',t);o.value=v;type.append(o);}type.value=filter.type;controls.append(search,type,button('刷新',open));dialog.append(controls);
 const eligible=d=>!['queued','understanding','generating'].includes(d.status),found=()=>list.filter(d=>(!filter.q||d.name.toLowerCase().includes(filter.q.toLowerCase()))&&(!filter.type||d.type===filter.type));
 const batch=el('div',undefined,'library-batch'),count=el('span'),all=button('全选当前筛选结果',()=>{found().filter(eligible).forEach(d=>selected.add(d.id));cards();}),clear=button('取消全选',()=>{selected.clear();cards();}),remove=button('删除所选',async()=>{const ids=[...selected];if(!ids.length||!confirm('确定删除选中的 '+ids.length+' 个方案吗？这些方案的全部历史版本也将从历史记录移除。'))return;dialog.querySelectorAll('button,input,select').forEach(n=>n.disabled=true);try{const result=await api('/api/designs/delete',{ids});window.workbenchHistory?.removed(result.deletedJobIds);list=list.filter(d=>!result.deletedIds.includes(d.id));selected.clear();selecting=false;renderList();message.textContent='已删除 '+result.deletedIds.length+' 个方案。';}catch(e){renderList();throw e;}});remove.className='delete-designs';batch.append(count,all,clear,remove);if(selecting)dialog.append(batch);const grid=el('div',undefined,'library-grid');dialog.append(grid);
 function cards(){grid.replaceChildren();count.textContent='已选择 '+selected.size+' 个方案';remove.disabled=!selected.size;clear.disabled=!selected.size;all.disabled=!found().some(eligible);if(!found().length)grid.append(el('p','这里还没有符合条件的方案。'));for(const d of found()){const card=button('',()=>{if(selecting){if(selected.has(d.id))selected.delete(d.id);else selected.add(d.id);cards();}else return show(d.id);});card.className='design-card'+(selected.has(d.id)?' is-selected':'');if(selecting){card.setAttribute('role','checkbox');card.setAttribute('aria-checked',String(selected.has(d.id)));card.setAttribute('aria-label','选择方案：'+d.name);card.disabled=!eligible(d);const mark=el('span',selected.has(d.id)?'✓':'','selection-mark');mark.setAttribute('aria-hidden','true');card.append(mark);}if(d.cover){const img=el('img');img.src=d.cover;img.alt=d.name;img.loading='lazy';card.append(img);}else card.append(el('div','尚无完成图片','no-cover'));const caption=el('div',undefined,'card-text');caption.append(el('strong',d.name),el('small',labels[d.type]+' · '+d.versionCount+' 个成图版本'),el('small',new Date(d.updatedAt).toLocaleString('zh-CN')));caption.append(el('small',(states[d.status]||d.status)+(selecting&&!eligible(d)?' · 完成后可删除':'')));card.append(caption);grid.append(card);}}
 search.oninput=()=>{filter.q=search.value;selected.clear();cards();};type.onchange=()=>{filter.type=type.value;selected.clear();cards();};cards();}
 async function show(id,version){detail=await api('/api/designs/'+id);current=detail.jobs.find(j=>j.id===(version||detail.selectedId||detail.coverId))||detail.jobs.at(-1);renderDetail();}
 const complete=()=>detail.jobs.filter(j=>j.status==='complete'&&j.result);
 function versionName(j){const i=complete().findIndex(v=>v.id===j.id);return i>=0?'V'+(i+1):states[j.status];}
 function download(url,name){const a=el('a');a.href=url;a.download=name;a.click();}
 function renderDetail(){const h=top(detail.name);h.append(button('返回方案库',open));const container=el('div',undefined,'library-detail'),main=el('div'),side=el('div',undefined,'library-side');if(current.result){const img=el('img');img.className='library-hero';img.src=current.result.url;img.alt=detail.name+' '+versionName(current);main.append(img);}else main.append(el('p','本次尝试：'+(states[current.status]||current.status)+(current.error?' · '+current.error:'')));
 side.append(el('h3',versionName(current)),el('p',current.refinement?.note||'原始图'));
 if(current.result){side.append(button('下载图片',()=>download(current.result.url,detail.name+'-'+versionName(current)+'.png')),button('继续微调这一版',async()=>{await window.workbenchHistory.view(current.id);dialog.close();document.querySelector('.refinement-note')?.focus();}));}
 const strip=el('div',undefined,'version-strip');for(const j of complete()){const c=button('',()=>{current=j;renderDetail();});c.className='version-card'+(j.id===current.id?' active':'');const img=el('img');img.src=j.result.url;img.alt=versionName(j);c.append(img,el('strong',versionName(j)),el('small',j.refinement?.note||'原始图'));strip.append(c);}main.append(strip);container.append(main,side);dialog.append(container);}
 window.openDesignLibrary=open;
 // 折叠只包裹原节点，不重建表单，不丢失输入和事件。
 function foldInputs(){document.querySelectorAll('#editor>.panel').forEach((panel,i)=>{if(panel.parentElement.classList.contains('input-fold'))return;const d=el('details',undefined,'input-fold');d.open=true;d.append(el('summary',panel.querySelector('h2,h3')?.textContent||'需求配置'));panel.before(d);d.append(panel);});}
 new MutationObserver(foldInputs).observe(document.getElementById('editor'),{childList:true});foldInputs();
})();
