const fs=require('node:fs/promises');const path=require('node:path');
module.exports=async function historyStore({dataDir,jobs,mediaFile}){
 const file=path.join(dataDir,'design-library.json');let metadata={};try{metadata=JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}let writes=Promise.resolve();
 const persist=()=>{const snapshot=JSON.stringify(metadata,null,2);writes=writes.then(async()=>{await fs.writeFile(file+'.tmp',snapshot,{mode:0o600});await fs.rename(file+'.tmp',file);});return writes;};
 const fail=(msg,status=400)=>{throw Object.assign(new Error(msg),{status});};
 function root(j){let current=j;const seen=new Set();while(current.parentId&&jobs.has(current.parentId)&&!seen.has(current.id)){seen.add(current.id);current=jobs.get(current.parentId);}return current.rootId&&jobs.has(current.rootId)?current.rootId:current.id;}
 function group(id){if(metadata[id]?.deletedAt)fail('方案已删除。',404);const items=[...jobs.values()].filter(j=>root(j)===id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));if(!items.length)fail('方案不存在。',404);return items;}
 function summary(id,items){const m=metadata[id]||{},complete=items.filter(j=>j.status==='complete'&&j.result),selected=complete.find(j=>j.id===m.selectedId),cover=selected||complete.at(-1),first=items[0];return {id,name:m.name||`${({model:'模特',product:'单品',size:'尺寸'})[first.request.type]} · ${first.request.size?.garment||first.request.product?.garment||first.request.garments?.map(g=>g.name).join('＋')||'服装方案'}`,type:first.request.type,archived:!!m.archived,selectedId:selected?.id||null,cover:cover?.result.url||null,coverId:cover?.id||null,createdAt:first.createdAt,updatedAt:items.at(-1).createdAt,versionCount:complete.length,attemptCount:items.length,status:items.at(-1).status};}
 return {list(){const groups=new Map();for(const j of jobs.values()){const id=root(j);if(metadata[id]?.deletedAt)continue;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(j);}return [...groups].map(([id,items])=>summary(id,items.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));},
 isDeleted(id){const j=jobs.get(id);return !!(j&&metadata[root(j)]?.deletedAt);},
 async remove(ids){if(!Array.isArray(ids)||!ids.length||ids.some(id=>typeof id!=='string'))fail('请选择需要删除的方案。');const selected=[...new Set(ids)].map(id=>({id,items:group(id)}));if(selected.some(d=>d.items.some(j=>['queued','understanding','generating'].includes(j.status))))fail('所选方案有进行中的任务，请完成后再删除。',409);const deletedAt=new Date().toISOString();for(const d of selected)metadata[d.id]={...(metadata[d.id]||{}),deletedAt};await persist();return {deletedIds:selected.map(d=>d.id),deletedJobIds:selected.flatMap(d=>d.items.map(j=>j.id))};},
 detail(id){const items=group(id);return {...summary(id,items),jobs:items};},
 async update(id,patch){const items=group(id),next={...(metadata[id]||{})};if(patch.name!==undefined){if(typeof patch.name!=='string'||!patch.name.trim()||patch.name.length>80)fail('名称需为1至80字。');next.name=patch.name.trim();}if(patch.archived!==undefined){if(typeof patch.archived!=='boolean')fail('归档状态无效。');next.archived=patch.archived;}if(patch.selectedId!==undefined){if(patch.selectedId!==null&&!items.some(j=>j.id===patch.selectedId&&j.status==='complete'&&j.result))fail('只能选定本方案的已完成版本。');next.selectedId=patch.selectedId;}metadata[id]=next;await persist();return this.detail(id);},
 annotation(id){if(!jobs.has(id))fail('任务不存在。',404);return metadata[root(jobs.get(id))]?.annotations?.[id]||null;},
 async saveAnnotation(id,value){const j=jobs.get(id);if(!j||j.request.type!=='size'||!j.result)fail('只能保存已生成尺寸图的标注。');if(!value||!Array.isArray(value.rows)||value.rows.length>100||typeof value.source!=='string'||value.source!==JSON.stringify(j.request.size))fail('标注数据或来源无效。');const values=j.request.size.values||{};if(value.rows.length!==Object.keys(values).length)fail('标注项目不匹配。');const seen=new Set();for(const row of value.rows){if(!Object.hasOwn(values,row.name)||seen.has(row.name)||String(values[row.name])!==row.value||(j.request.size.units?.[row.name]??'cm')!==row.unit||!['文字','横向','竖向','斜向'].includes(row.kind))fail('标注不可改变原始尺寸。');seen.add(row.name);for(const k of ['x','y','ax','ay','bx','by'])if(!Number.isFinite(row[k])||row[k]<0||row[k]>1)fail('标注位置无效。');}const rid=root(j);metadata[rid]||={};metadata[rid].annotations||={};metadata[rid].annotations[id]=value;await persist();return {saved:true};},
 async export(id){const d=this.detail(id),urls=new Set();for(const j of d.jobs){j.assets.forEach(a=>urls.add(a.url));if(j.result)urls.add(j.result.url);}const files=[];for(const url of urls)files.push({url,base64:(await fs.readFile(mediaFile(url))).toString('base64')});return {format:'fabric-pig-design-backup-v1',exportedAt:new Date().toISOString(),design:d,metadata:metadata[id]||{},files};}
 };
};
