(() => {
 if(location.protocol==='file:')return;
 const api=async(url,body)=>{const response=await fetch(url,{...(body?{method:'POST',body:JSON.stringify(body)}:{}),headers:{'Content-Type':'application/json','X-Workbench':'1'}});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;};
 const stateKey='fabric-pig.live-workspace.v1';
 const jobKey='fabric-pig.live-jobs.v1';
 let current={},jobs={},history=[],busy=false,polling=false,restoring=true,expectedProvider='';
 try{current=JSON.parse(localStorage.getItem(jobKey)||'{}');}catch{}
 let previous;try{previous=JSON.parse(localStorage.getItem(stateKey)||'null');}catch{}
 if(previous){Object.assign(garments,previous.garments);Object.assign(product,previous.product);Object.assign(size,previous.size);models.splice(0,models.length,...previous.models);Object.assign(styling[0],previous.styling);model=previous.model;outfit=previous.outfit;combination=previous.combination;}
 const saveState=()=>{try{localStorage.setItem(stateKey,JSON.stringify({garments,product,size,models,styling:styling[0],model,outfit,combination}));localStorage.setItem(jobKey,JSON.stringify(current));}catch{notify('浏览器保存失败；已提交任务仍保存在本机服务端。');}};
 const style=document.createElement('style');style.textContent='.live-result{display:block;width:100%;border-radius:10px}.live-status{padding:18px;border:1px solid #e4d5df;background:#fff8fb;border-radius:10px;white-space:pre-wrap}.live-link{display:inline-block;padding:10px 14px;margin:10px 8px 10px 0;background:#993b59;color:white;border-radius:7px;text-decoration:none}.live-history{width:100%;margin:10px 0}.live-confirmed{max-height:180px;max-width:130px;object-fit:contain}.live-annotation{max-width:100%;touch-action:none;cursor:move}.live-details pre{white-space:pre-wrap;word-break:break-word;font-size:12px}.live-extra{margin-top:18px}.live-extra input{margin:8px 0}';document.head.append(style);
 document.querySelector('header>.badge').textContent='模型服务 · 本机运行';
 document.querySelector('.preview-head .badge').textContent='真实生成';
 document.querySelector('.preview-body>p.note').textContent='每次一个方案；有待确认问题时先整理，确认后再生图。';
 document.querySelector('.notice').textContent='点击生成会把本次素材及需求发送到当前选择的模型服务并按用量计费。成图保存在本机。';
 const historySelect=document.createElement('select');historySelect.id='task-history';historySelect.className='field live-history';historySelect.setAttribute('aria-label','查看已保存任务');document.querySelector('.preview-body').insertBefore(historySelect,$('preview-title'));historySelect.onchange=async()=>{try{const job=await api('/api/jobs/'+historySelect.value);current[job.request.type]=job.id;jobs[job.id]=job;drafts[job.request.type]||={};drafts[job.request.type].historyId=job.id;saveState();refreshPreview();}catch(e){notify(e.message);}};
 document.querySelector('#prompt-panel h2').textContent='1 · 信息搜集汇总版';
 document.querySelector('#copy-prompt').textContent='复制原始汇总';
 $('full-prompt').setAttribute('aria-label','信息搜集汇总版');$('full-prompt').readOnly=false;
 document.querySelector('#prompt-panel .note').textContent='程序汇总当前填写内容和素材用途。可直接修改；点击优化时，这份原稿与对应原图一起交给 AI。修改尺寸请回到上方尺寸表单。';
 const controls=document.createElement('div');controls.innerHTML='<button id="reset-summary">从当前表单重新汇总</button> <button id="optimize-prompt">优化提示词</button><p class="note" id="process-status"></p>';$('prompt-panel').append(controls);
 const optimized=document.createElement('section');optimized.className='panel';optimized.id='optimized-panel';optimized.style.marginTop='20px';optimized.innerHTML='<div class="panel-head"><h2>2 · 优化后的生图指令</h2><button id="copy-optimized">复制生图指令</button></div><p class="note">整理完成后显示实际发送给生图模型的完整指令，可修改后再生成。参考图沿用该次整理任务的素材。</p><textarea id="optimized-prompt" class="field" aria-label="优化后的生图指令" style="width:100%;min-height:320px" placeholder="点击第一步的“优化提示词”后，在这里查看结果。"></textarea><button id="generate-reviewed">确认指令并生成图片</button>';$('prompt-panel').after(optimized);
 const draftsKey='fabric-pig.process-drafts.v1';let drafts={};try{drafts=JSON.parse(localStorage.getItem(draftsKey)||'{}');}catch{}
 const saveDrafts=()=>localStorage.setItem(draftsKey,JSON.stringify(drafts));
 const source=()=>JSON.stringify(packGenerationRequest());
 function draft(){return drafts[type]||(drafts[type]={});}
 function syncProcess(){
  const d=draft(),src=source(),job=jobs[current[type]];
  if(d.source!==src&&!d.manual){d.raw=buildFullPrompt();d.source=src;}
  if(d.raw===undefined){d.raw=buildFullPrompt();d.source=src;}
  if(document.activeElement!==$('full-prompt'))$('full-prompt').value=d.raw;
  const historical=job&&d.historyId===job.id;
  const stale=!historical&&(d.source!==src||(job&&(job.request.原始汇总!==d.raw||d.jobId!==job.id)));
  $('full-prompt').readOnly=!!historical;
  if(historical)$('full-prompt').value=job.request.原始汇总||JSON.stringify(job.request,null,2);
  if(job?.imagePrompt){d.optimized||={};if(d.optimized[job.id]===undefined)d.optimized[job.id]=job.imagePrompt;}
  if(document.activeElement!==$('optimized-prompt'))$('optimized-prompt').value=job?.imagePrompt?(d.optimized?.[job.id]||''):'';
  const running=job&&['queued','understanding','generating'].includes(job.status);
  $('optimize-prompt').disabled=busy||!!running||restoring||!!historical;
  $('generate-reviewed').disabled=busy||stale||job?.status!=='ready';
  $('optimized-prompt').readOnly=job?.status!=='ready';
  $('process-status').textContent=historical?'正在审阅历史任务：两栏及生图素材均来自该任务，上方表单不参与。点击“从当前表单重新汇总”可返回新任务。':stale?'表单、原稿或当前任务已变更。请重新汇总或优化，避免使用不匹配的指令。':job?.status==='ready'?'优化完成。请检查第二栏，再确认生成图片。':job?.status==='waiting'?'存在待确认问题，请在预览区补充确认。':'先优化提示词，再确认生成图片。';
  saveDrafts();
 }
 updateFullPrompt=syncProcess;
 $('full-prompt').addEventListener('input',()=>{const d=draft();d.raw=$('full-prompt').value;d.manual=true;d.source=source();syncProcess();});
 $('optimized-prompt').addEventListener('input',()=>{const job=jobs[current[type]];if(job){draft().optimized[job.id]=$('optimized-prompt').value;saveDrafts();}});
 $('reset-summary').onclick=()=>{Object.assign(draft(),{raw:buildFullPrompt(),source:source(),manual:false,historyId:null});syncProcess();};
 $('optimize-prompt').onclick=()=>generatePlans();
 $('copy-optimized').onclick=async()=>{try{await navigator.clipboard.writeText($('optimized-prompt').value);notify('生图指令已复制');}catch{notify('复制失败，请手动选择文本复制。');}};
 $('generate-reviewed').onclick=async()=>{if(busy||$('generate-reviewed').disabled)return;busy=true;syncProcess();try{const job=await api('/api/jobs/'+current[type]+'/generate',{prompt:$('optimized-prompt').value});jobs[job.id]=job;}catch(e){notify(e.message);}finally{busy=false;refreshPreview();}};
 const nativeModel=renderModel,nativeProduct=renderProduct,nativeSize=renderSize,nativePack=packGenerationRequest,nativeSummary=buildFullPrompt,nativeRender=render;
 garmentImage=src=>src.startsWith('/')||src.startsWith('blob:')?src:'assets/'+src;
 async function upload(file){if(file.size>20*1024*1024)throw Error('图片不能超过 20 MB');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});return (await api('/api/uploads',{data})).url;}
 loadGarmentFile=async file=>{if(!file||!garmentUploadTarget)return;const {owner,target,key}=garmentUploadTarget;try{const url=await upload(file);if(key==='ref'&&!owner.mods.includes(target))return;target[key]=url;saveState();render();notify('图片已保存到本机，生成时会随任务发送至当前模型服务。');}catch(e){notify(e.message);}};
 loadModelFile=async file=>{if(!file)return;const mode=uploadMode,target=replaceTarget;try{const src=await upload(file);if(mode==='replace'&&models.find(x=>x.id===target)){Object.assign(models.find(x=>x.id===target),{src,local:true});model=target;}else{model=Math.max(...models.map(x=>x.id))+1;models.push({id:model,src,local:true});}saveState();render();}catch(e){notify(e.message);}};
 renderModel=()=>nativeModel().replace('仅本地预览，刷新后重置。','上传后保存到本机；生成时发送至当前模型服务。').replace('仅本地预览，不发送服务器；刷新后恢复预设素材。','上传后保存到本机；只在点击生成时发送至当前模型服务。').replace('</div></div><p class="note">支持 JPG','<button id="no-model">不指定模特身份</button></div></div><p class="note">支持 JPG')+'<section class="panel"><button id="remove-base">移除当前单品基础图</button> <button id="no-model">不指定模特身份</button><p class="note">仅文字设计时，可移除基础图、修改参考和模特身份，直接填写需求。</p></section>';
 const activeState=()=>type==='product'?product[productGarment]:size[sizeGarment];
 confirmedBlock=(mode,g)=>{const state=mode==='product'?product[g]:size[g];return `<div class="source">${state.reference?`<img class="live-confirmed" src="${esc(state.reference)}" alt="已确认设计图">`:'<div class="empty-image">确认图未上传</div>'}<div><h3>${g}的已确认设计图</h3><button id="choose-confirmed">${state.reference?'替换确认图':'上传确认图'}</button></div></div>`;};
 const extra=()=>{const s=activeState();return `<section class="panel live-extra"><h3>补充参考与说明</h3><p class="note">${type==='product'?'可补充同款背面或细节参考；缺少背面时按同款风格合理补全。内置模板只控制拼图展示方式，不替代确认款式。':'需要背面或细节时，可上传相应参考。尺寸由程序叠加，可调整文字和测量线位置，不推算未填写的尺寸。'}</p><button id="add-extra-image">上传补充参考</button>${(s.extra||[]).map((a,i)=>`<div><img class="live-confirmed" src="${esc(a.url)}" alt="补充参考"><input class="field" data-extra-role="${i}" placeholder="说明这张图的用途" value="${esc(a.role)}"><button data-remove-extra="${i}">移除</button></div>`).join('')}<label>本次补充要求<textarea id="confirmed-note" class="field" placeholder="例如：只展示正面；胸围为整圈围度；肩宽为左右肩端点距离">${esc(s.note||'')}</textarea></label></section>`;};
 renderProduct=()=>nativeProduct()+extra();renderSize=()=>nativeSize()+`<section class="panel"><h3>标注版式参考</h3><p class="note">只借用主体、细节与标注留白的排版，不借用衣服或数字。此参考会随新任务发送给当前模型。</p>${activeState().layoutRef?`<img class="live-confirmed" src="${esc(activeState().layoutRef)}" alt="标注版式参考">`:''}<button id="choose-layout">${activeState().layoutRef?'替换':'上传'}版式参考</button> <button id="remove-layout">移除版式参考</button> <button id="example-layout">使用已认可标注例图</button></section>`+extra();
 packGenerationRequest=()=>{const r=nativePack();if(type==='model'){r.model.reference=model?models.find(x=>x.id===model)?.src:null;r.model.stylingSource='表单默认沿用值不是显式修改；用户在服装说明中的明确改款优先';}else{const s=activeState();r[type].reference=s.reference||null;r[type].extra=s.extra||[];r[type].note=s.note||'';if(type==='size')r.size.layoutReference=s.layoutRef||null;if(type==='product'){r.product.subtype=s.subtype||null;r.product.layout=r.product.garment==='连衣裙'?'白底竖向3:4拼接图，自动使用连衣裙模板；上方约一半左正面右背面，下方按所选顺序排列细节，五至六项分两行三列；模板只提供布局和摄影效果。':'白底拼接图，画幅6:5，上方左正面右背面，下方按所选顺序排列细节；上衣自动使用上衣模板，裤子自动使用裤子模板，模板只提供布局和摄影效果。';}}return r;};
 // 原函数需要安全处理“没有指定身份”。

 buildFullPrompt=()=>{if(type==='model')return nativeSummary().replace('模特身份使用未提供，不借用该图的服装替代上述单品。','未指定模特身份，按整体风格合理补充单人模特。');const r=packGenerationRequest();return JSON.stringify({类型:labels[type],用户原始填写:r[type],通用要求:type==='product'?'保持确认款式；套头款门襟替换为领口并去重；缺少背面时按同款风格合理补全并注明推定；尺寸不得推算。':'保持确认款式；按逐项单位原样保留数值、区间与倍率；版式参考只借用排版；底图不画文字和线条，由程序叠加可编辑文字及尺寸线；端点由用户调整，不阻塞底图、不推算尺寸。'},null,2);};
 render=()=>{nativeRender();saveState();};
 async function collect(){const request=packGenerationRequest(),assets=[];request.uiSnapshot={garments:structuredClone(garments),product:structuredClone(product),size:structuredClone(size),models:structuredClone(models),styling:structuredClone(styling[0]),model,outfit,combination,garment,productGarment,sizeGarment};request.用户原始填写=type==='model'?{单品:activeGarments().map(name=>({name,...structuredClone(garments[name])})),模特身份:model,展示组合:combination,穿搭:structuredClone(styling[0])}:structuredClone(activeState());const add=(url,role)=>{if(!url)return null;const id='ref-'+(assets.length+1);assets.push({id,url:url.startsWith('/')||url.startsWith('assets/')?url:'assets/'+url,role});return id;};
 if(type==='model'){for(const g of request.garments){g.base=add(g.base,g.name+'基础图');for(const [i,m]of g.changes.entries())m.ref=add(m.ref,g.name+'第'+(i+1)+'条'+m.kind+'修改参考，仅用于'+(m.part||'待确认部位'));}request.model.reference=add(request.model.reference,'模特身份参考');}
 else{const s=request[type];s.reference=add(s.reference,'已确认设计图');if(type==='size')s.layoutReference=add(s.layoutReference,'标注版式参考：只借用布局、细节排版和留白，不借用款式或任何数字');s.extra=s.extra.map(a=>({id:add(a.url,a.role||'补充参考用途待确认'),role:a.role}));}
 request.原始汇总=draft().raw??buildFullPrompt();return {request,assets};}
 const statuses={ready:'指令已整理，等待确认生图',queued:'已排队',understanding:'正在读取素材、整理需求…',waiting:'需要你确认以下内容',generating:'正在结合原图生成…',complete:'生成完成',failed:'生成未完成'};
 refreshPreview=()=>{historySelect.innerHTML='<option value="">查看已保存任务</option>'+history.filter(j=>j.type===type).map(j=>`<option value="${esc(j.id)}" ${current[type]===j.id?'selected':''}>${esc(new Date(j.createdAt).toLocaleString('zh-CN'))} · ${esc(statuses[jobs[j.id]?.status||j.status])}</option>`).join('');updateFullPrompt();$('preview-title').textContent=labels[type];const job=jobs[current[type]];const running=job&&['queued','understanding','generating'].includes(job.status);$('generate').disabled=busy||!!running||restoring;$('generate').textContent=busy?'提交中…':running?'任务进行中…':'优化提示词';
 if(!job){$('preview-content').innerHTML='<p class="live-status">上传或填写要求后，先优化提示词，再检查页面下方的两份内容并确认生图。</p>';return;}
 $('preview-content').innerHTML=`<p class="live-status">${job.provider==='openai'?'OpenAI':job.provider==='ark'?'豆包':'历史任务'} · ${esc(statuses[job.status])}${job.error?'\n'+esc(job.error):''}</p>${job.result?`<img class="live-result" src="${esc(job.result.url)}" alt="AI 生成结果"><a class="live-link" download="${labels[job.request.type]}.png" href="${esc(job.result.url)}">下载${job.request.type==='size'?'无标注底图':'原图'}</a><button id="use-result">用于确认款式</button>`:''}${job.status==='waiting'?`<ol>${job.analysis.待确认问题.map(q=>`<li>${esc(q.问题||q)}${q.原因?'<p>'+esc(q.原因)+'</p>':''}</li>`).join('')}</ol><textarea id="answer" class="field" placeholder="填写确认意见或补充要求"></textarea><button id="answer-job">确认并继续</button>`:''}${job.analysis?`<details class="live-details"><summary>查看需求整理结果</summary><pre>${esc(JSON.stringify(job.analysis,null,2))}</pre></details>`:''}<p class="note">任务 ${esc(job.id)}<br>刷新页面可恢复。失败后不会自动重试付费请求。</p>`;
 if(job.result&&job.request.type==='size')renderAnnotation(job);
 if(job.result||job.parentId)renderRefinement(job);
 };
 async function poll(){if(polling)return;polling=true;try{for(const id of Object.values(current)){if(!id)continue;const before=jobs[id];if(!before||['queued','understanding','generating'].includes(before.status)){jobs[id]=await api('/api/jobs/'+id);if(current[type]===id&&(!before||before.status!==jobs[id].status))refreshPreview();}}}catch(e){notify('任务状态读取失败：'+e.message);}finally{polling=false;}}
 generatePlans=async()=>{if(busy)return;if(draft().historyId){notify('请先点击“从当前表单重新汇总”，再优化新任务。');return;}busy=true;refreshPreview();try{const submittedSource=source();const payload=await collect();const signature=JSON.stringify(payload);let pending;try{pending=JSON.parse(localStorage.getItem('fabric-pig.pending')||'null');}catch{}if(!pending||pending.signature!==signature){pending={signature,requestId:crypto.randomUUID()};localStorage.setItem('fabric-pig.pending',JSON.stringify(pending));}const job=await api('/api/jobs',{...payload,reviewBeforeGenerate:true,expectedProvider,requestId:pending.requestId});current[job.request.type]=job.id;drafts[job.request.type].jobId=job.id;drafts[job.request.type].source=submittedSource;saveDrafts();jobs[job.id]=job;history.unshift({id:job.id,type:job.request.type,createdAt:job.createdAt,status:job.status});localStorage.removeItem('fabric-pig.pending');saveState();}catch(e){notify(e.message);}finally{busy=false;refreshPreview();}};
 document.addEventListener('click',e=>{const id=e.target.closest('button')?.id;if(!['choose-layout','remove-layout','example-layout','add-measure','try-annotations'].includes(id))return;e.preventDefault();e.stopImmediatePropagation();const s=activeState();if(id==='choose-layout'){filePurpose={state:s,layout:true};fileInput.value='';fileInput.click();}if(id==='example-layout'){s.layoutRef='assets/annotation-layout-skirt.png';render();}if(id==='remove-layout'){delete s.layoutRef;render();}if(id==='add-measure'){const name=$('custom-measure-name').value.trim();if(!name||name.length>40||['__proto__','constructor','prototype'].includes(name)){notify('请输入1至40字的标注名称');return;}if(measureFields().includes(name)){notify('该标注项已存在');return;}s.customFields||=[];s.customFields.push(name);render();}if(id==='try-annotations'){const request=packGenerationRequest();$('preview-content').innerHTML='<p class="note">当前确认图试标注，不调用 AI；不会自动移除人物或改变原图布局。</p>';renderAnnotation({id:'preview-'+sizeGarment+'-'+(s.subtype||'')+'-'+s.reference,request,result:{url:s.reference}});}saveState();},true);
 document.addEventListener('change',e=>{if(e.target.id==='product-subtype'){activeState().subtype=e.target.value;saveState();updateFullPrompt();}});
 document.addEventListener('change',e=>{const d=e.target.dataset,s=activeState();if(type!=='size')return;if(d.measureUnit!==undefined){s.units||={};s.units[d.measureUnit]=e.target.value;}else if(d.measureLine!==undefined){s.lineTypes||={};s.lineTypes[d.measureLine]=e.target.value;}else if(e.target.id==='size-views')s.views=e.target.value;else return;saveState();updateFullPrompt();});
 document.addEventListener('input',e=>{if(e.target.id==='size-detail-note'){activeState().detailNote=e.target.value;saveState();updateFullPrompt();}});
 const fileInput=document.createElement('input');fileInput.type='file';fileInput.accept='image/jpeg,image/png,image/webp';fileInput.hidden=true;document.body.append(fileInput);let filePurpose;
 fileInput.onchange=async()=>{const file=fileInput.files[0],purpose=filePurpose;if(!file)return;try{const url=await upload(file);if(purpose.layout){purpose.state.layoutRef=url;}else if(purpose.extra){purpose.state.extra||=[];purpose.state.extra.push({url,role:'补充参考'+(purpose.state.extra.length+1)});}else{purpose.state.reference=url;purpose.state.confirmed=true;}saveState();render();}catch(e){notify(e.message);}};
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const id=b.id;if(['choose-confirmed','add-extra-image','no-model','remove-base','answer-job','use-result'].includes(id)||b.dataset.removeExtra!==undefined){e.stopImmediatePropagation();e.preventDefault();}
 if(id==='choose-confirmed'||id==='add-extra-image'){filePurpose={state:activeState(),extra:id==='add-extra-image'};fileInput.value='';fileInput.click();}
 if(id==='no-model'){model=0;render();}
 if(id==='remove-base'){garments[garment].base='';render();}
 if(b.dataset.removeExtra!==undefined){activeState().extra.splice(Number(b.dataset.removeExtra),1);render();}
 if(id==='answer-job'){b.disabled=true;try{const job=await api('/api/jobs/'+current[type]+'/answer',{answer:$('answer').value});jobs[job.id]=job;refreshPreview();}catch(e){notify(e.message);b.disabled=false;}}
 if(id==='use-result'){const job=jobs[current[type]];const g=job.request.garments?.[0]?.name||job.request[job.request.type]?.garment||'上衣';product[g].reference=job.result.url;product[g].confirmed=true;size[g].reference=job.result.url;size[g].confirmed=true;saveState();notify('已设为'+g+'的确认款式，可切换到单品展示或尺寸标注。');}
 },true);
 document.addEventListener('input',e=>{if(e.target.id==='confirmed-note'){activeState().note=e.target.value;updateFullPrompt();}if(e.target.dataset.extraRole!==undefined)activeState().extra[Number(e.target.dataset.extraRole)].role=e.target.value;saveState();});
 const refinementKey='fabric-pig.refinement-drafts.v1';let refinementDrafts={};try{refinementDrafts=JSON.parse(localStorage.getItem(refinementKey)||'{}');}catch{}
 function saveRefinement(){try{localStorage.setItem(refinementKey,JSON.stringify(refinementDrafts));}catch{notify('微调草稿保存失败，请保留文字。');}}
 function renderRefinement(job){
  const section=document.createElement('section');section.className='refinement-panel panel';$('preview-content').append(section);
  const root=job.rootId||job.id;const versions=history.filter(j=>j.id===root||j.rootId===root);const heading=document.createElement('h3');heading.textContent='成图版本与微调';section.append(heading);
  const picker=document.createElement('select');picker.className='field refinement-versions';picker.setAttribute('aria-label','选择成图版本');for(const v of versions){const option=document.createElement('option');option.value=v.id;option.selected=v.id===job.id;option.textContent=(v.revision?'微调第'+v.revision+'版':'原始版')+' · '+new Date(v.createdAt).toLocaleString('zh-CN')+' · '+(statuses[jobs[v.id]?.status||v.status]||v.status);picker.append(option);}section.append(picker);
  picker.onchange=async()=>{try{const selected=await api('/api/jobs/'+picker.value);jobs[selected.id]=selected;current[selected.request.type]=selected.id;drafts[selected.request.type].historyId=selected.id;saveState();refreshPreview();}catch(e){notify(e.message);}};
  if(job.parentId){const compare=document.createElement('div');compare.className='refinement-compare';compare.innerHTML='<p class="note">修改前</p>';section.append(compare);api('/api/jobs/'+job.parentId).then(parent=>{if(!section.isConnected)return;const img=document.createElement('img');img.className='live-result';img.alt='本次微调前的图片';img.src=parent.result.url;compare.append(img);if(job.result){const label=document.createElement('p');label.className='note';label.textContent='修改后';const after=document.createElement('img');after.className='live-result';after.alt='本次微调后的图片';after.src=job.result.url;compare.append(label,after);}}).catch(e=>{if(section.isConnected)notify(e.message);});const note=document.createElement('p');note.className='note';note.textContent='本版修改：'+job.refinement.note;section.append(note);}
  if(job.status!=='complete'||!job.result)return;
  const d=refinementDrafts[job.id]||(refinementDrafts[job.id]={note:'',references:[]});
  const label=document.createElement('label');label.textContent='修改说明';const textarea=document.createElement('textarea');textarea.className='field refinement-note';textarea.maxLength=10000;textarea.placeholder='例如：只把纽扣改成深棕色，其他保持不变。请明确部位和目标效果。';textarea.value=d.note;label.append(textarea);section.append(label);textarea.oninput=()=>{d.note=textarea.value;saveRefinement();};
  const refs=document.createElement('div');refs.className='refinement-references';section.append(refs);
  function showRefs(){refs.replaceChildren();d.references.forEach((r,i)=>{const row=document.createElement('div'),img=document.createElement('img'),role=document.createElement('input'),remove=document.createElement('button');img.src=r.url;img.className='live-confirmed';img.alt='微调参考图'+(i+1);role.className='field';role.setAttribute('aria-label','微调参考图'+(i+1)+'用途');role.value=r.role;role.maxLength=150;role.oninput=()=>{r.role=role.value;saveRefinement();};remove.textContent='移除此参考';remove.onclick=()=>{d.references.splice(i,1);saveRefinement();showRefs();};row.append(img,role,remove);refs.append(row);});}showRefs();
  const uploadButton=document.createElement('button');uploadButton.className='refinement-upload';uploadButton.textContent='上传微调参考（最多2张）';const file=document.createElement('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.hidden=true;section.append(uploadButton,file);let uploading=false;
  uploadButton.onclick=()=>{if(d.references.length>=2){notify('最多两张微调参考，请先移除一张。');return;}file.value='';file.click();};file.onchange=async()=>{if(!file.files[0])return;uploading=true;submit.disabled=true;uploadButton.disabled=true;try{const url=await upload(file.files[0]);d.references.push({url,role:'仅用于本次指定修改部位'});saveRefinement();showRefs();}catch(e){notify(e.message);}finally{uploading=false;submit.disabled=false;uploadButton.disabled=false;}};
  const notice=document.createElement('p');notice.className='note';notice.textContent='以当前选中的成图为基础，点击后直接调用原任务的模型服务，按实际用量计费。新版本单独保存，原图不覆盖。'+(job.request.type==='size'?'尺寸图只修改底图，新版本需重新检查标注位置。':'');section.append(notice);
  const submit=document.createElement('button');submit.className='primary refinement-submit';submit.textContent='按此要求微调（生成新版本）';section.append(submit);
  submit.onclick=async()=>{if(busy||uploading)return;if(!d.note.trim()){notify('请先填写具体修改说明。');return;}const signature=JSON.stringify({note:d.note,references:d.references});if(d.pendingSignature!==signature){d.requestId=crypto.randomUUID();d.pendingSignature=signature;saveRefinement();}busy=true;submit.disabled=true;try{const child=await api('/api/jobs/'+job.id+'/refine',{requestId:d.requestId,note:d.note,references:d.references});jobs[child.id]=child;current[child.request.type]=child.id;drafts[child.request.type].historyId=child.id;if(!history.some(h=>h.id===child.id))history.unshift({id:child.id,type:child.request.type,createdAt:child.createdAt,status:child.status,parentId:child.parentId,rootId:child.rootId,revision:child.revision});saveState();saveDrafts();refreshPreview();}catch(e){notify(e.message);submit.disabled=false;}finally{busy=false;}};
 }
 function renderAnnotation(job){window.mountGarmentAnnotations($('preview-content'),job);}
 function clearDeletedHistory(ids){const deleted=new Set(ids);history=history.filter(j=>!deleted.has(j.id));for(const id of deleted)delete jobs[id];for(const kind of Object.keys(labels)){if(deleted.has(current[kind]))delete current[kind];for(const key of ['historyId','jobId'])if(deleted.has(drafts[kind]?.[key]))delete drafts[kind][key];}saveState();saveDrafts();}
 window.workbenchHistory={
 removed(ids){clearDeletedHistory(ids);refreshPreview();},
 async view(id){const j=await api('/api/jobs/'+id);jobs[j.id]=j;type=j.request.type;current[type]=j.id;draft().historyId=j.id;history=await api('/api/jobs');saveState();saveDrafts();render();},
 async copy(j){const r=j.request,s=r.uiSnapshot;
 // 保存当前工作区到浏览器备份；复制需求是显式操作，浏览方案不会走这里。
 localStorage.setItem('fabric-pig.before-copy',localStorage.getItem(stateKey)||'{}');
 if(s){Object.assign(garments,structuredClone(s.garments));Object.assign(product,structuredClone(s.product));Object.assign(size,structuredClone(s.size));models.splice(0,models.length,...structuredClone(s.models));Object.assign(styling[0],s.styling);model=s.model;outfit=s.outfit;combination=s.combination;garment=s.garment;productGarment=s.productGarment;sizeGarment=s.sizeGarment;}
 else{const src=id=>j.assets.find(a=>a.id===id)?.url||id;const raw=r.用户原始填写;
 if(r.type==='model'){outfit=r.outfit||'separates';for(const g of Object.values(garments)){g.base='';g.note='';g.mods=[];}for(const g of (raw?.单品||r.garments||[])){const name=g.name;if(!garments[name])continue;garments[name]={base:src(g.base)||'',note:g.note||'',mods:(g.mods||g.changes||[]).map(m=>({...m,ref:src(m.ref)||''}))};garment=name;}combination=r.model?.combination||'单人模特';Object.assign(styling[0],r.model?.styling||{});const ref=src(r.model?.reference);if(ref){model=Math.max(0,...models.map(m=>m.id))+1;models.push({id:model,src:ref,local:true});}else model=0;
 }else{const g=r[r.type].garment;if(r.type==='size')sizeGarment=g;else productGarment=g;const state=r.type==='size'?size[g]:product[g];Object.assign(state,raw||{});state.reference=src(r[r.type].reference);state.confirmed=true;state.note=r[r.type].note||'';state.extra=(r[r.type].extra||[]).map(a=>({url:src(a.id||a.url),role:a.role}));if(r.type==='size'){state.values=structuredClone(r.size.values);state.units=r.size.units||{};state.lineTypes=r.size.lineTypes||{};state.views=r.size.views||'正面';state.detailNote=r.size.detailNote||'';state.layoutRef=src(r.size.layoutReference)||'';state.customFields=Object.keys(state.values);}else state.selected=r.product.details||[];}}
 type=r.type;delete current[type];drafts[type]={};saveState();saveDrafts();render();notify('已复制为新方案草稿，原方案保留；尚未调用模型。');}
 };
 async function init(){try{const config=await api('/api/config');expectedProvider=config.providerId;document.querySelector('header>.badge').textContent=config.provider+(config.keyPresent?' · 已配置':' · 待配置密钥');if(!config.keyPresent)notify('请在管理后台 → 模型连接设置中保存 API Key。');document.querySelector('.notice').textContent='新任务将素材与要求发送到 '+config.provider+' 并按实际用量计费。优化和生图分两次提交，分别按用量计费。';history=await api('/api/jobs');const known=new Set(history.map(j=>j.id));clearDeletedHistory([...Object.values(current),...Object.values(drafts).flatMap(d=>[d.historyId,d.jobId])].filter(id=>id&&!known.has(id)));const linked=new URLSearchParams(location.search).get('job');if(linked&&history.some(j=>j.id===linked)){type=history.find(j=>j.id===linked).type;current[type]=linked;draft().historyId=linked;}for(const kind of Object.keys(labels))if(!current[kind])current[kind]=history.find(j=>j.type===kind)?.id;await poll();}catch(e){notify(e.message);}finally{restoring=false;render();}}
 init();setInterval(poll,2500);
})();
