const {test}=require('node:test');const assert=require('node:assert/strict');
const {openaiProvider}=require('./openai-provider.cjs');
const ready={状态:'可生成',任务类型:'模特上身图',待确认问题:[],生成指令:'米白色针织上衣'};
const job=()=>({request:{type:'model'},assets:[{id:'ref-1',role:'上衣基础图'}],answers:[],templates:{understand:'整理为 JSON',generate:'保留未修改部分'},imagePrompt:'仅改立领'});
test('OpenAI 理解采用 Responses，不发送方舟专有参数，原图随请求提交',async()=>{
 const original=global.fetch;try{global.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const b=JSON.parse(options.body);assert.equal(b.thinking,undefined);assert.equal(b.store,false);assert.equal(b.input[1].content[2].image_url,'data:image/png;base64,dGVzdA==');return Response.json({id:'resp-unit',status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(ready)}]}],usage:{total_tokens:100}});};const result=await openaiProvider.understand({job:job(),images:['data:image/png;base64,dGVzdA=='],config:{apiKey:'test-key',understandModel:'gpt-4.1'}});assert.deepEqual(result.analysis,ready);}finally{global.fetch=original;}
});
test('带多张原图用 multipart 编辑，纯文字用生成；只接受一张返回图',async()=>{
 const original=global.fetch;try{let mode='edit';global.fetch=async(url,options)=>{if(mode==='edit'){assert.equal(url,'https://api.openai.com/v1/images/edits');assert.equal(options.headers['Content-Type'],undefined);assert.equal(options.body.getAll('image[]').length,2);assert.equal(options.body.get('size'),'1536x2048');assert.equal(options.body.get('quality'),'high');assert.equal(options.body.has('response_format'),false);}else{assert.equal(url,'https://api.openai.com/v1/images/generations');assert.equal(JSON.parse(options.body).image,undefined);assert.equal(JSON.parse(options.body).quality,'high');}return Response.json({data:[{b64_json:'dGVzdA=='}],usage:{total_tokens:10}});};const result=await openaiProvider.generate({job:job(),images:['data:image/png;base64,dGVzdA==','data:image/jpeg;base64,dGVzdA=='],config:{apiKey:'test-key',imageModel:'gpt-image-2.5-sunburst'}});assert.equal(result.buffer.toString(),'test');mode='text';await openaiProvider.generate({job:job(),images:[],config:{apiKey:'test-key',imageModel:'gpt-image-2.5-sunburst'}});}finally{global.fetch=original;}
});
test('鉴权失败不回显服务商原始消息中的密钥，不自动重试',async()=>{const original=global.fetch;let calls=0;try{global.fetch=async()=>{calls++;return Response.json({error:{code:'invalid_api_key',message:'secret-should-not-leak'}},{status:401});};await assert.rejects(()=>openaiProvider.understand({job:job(),images:[],config:{apiKey:'secret-should-not-leak'}}),e=>!e.message.includes('secret-should-not-leak')&&e.message.includes('密钥'));assert.equal(calls,1);}finally{global.fetch=original;}});
test('内容审核拦截区分输入、输出与未知阶段，详情只保留安全字段且不重试',async()=>{
 const original=global.fetch;try{for(const stage of ['input','output',undefined]){let calls=0;global.fetch=async()=>{calls++;return Response.json({error:{code:'moderation_blocked',message:'secret-should-not-leak',moderation_details:stage?{moderation_stage:stage,categories:['sexual','secret-should-not-leak'],raw:'secret-should-not-leak'}:undefined}},{status:400});};await assert.rejects(()=>openaiProvider.generate({job:job(),images:[],config:{apiKey:'test-key'}}),e=>{assert.match(e.message,/内容审核未通过/);assert.doesNotMatch(e.message,/检查配置|secret-should-not-leak/);assert.equal(e.moderationDetails.stage,stage||'unknown');assert.deepEqual(e.moderationDetails.categories,stage?['sexual']:[]);assert.match(e.message,stage==='input'?/输入审核/:stage==='output'?/生成结果审核/:/未提供具体审核阶段/);return true;});assert.equal(calls,1);}}finally{global.fetch=original;}
});
